version: '3.7'

networks:
  default:
    external:
      name: whirlpool-net


services:

  whirlpool-fetch:
    container_name: whirlpool-fetch
    entrypoint: bash ./scripts/wait-for-it.sh
    environment:
      - NODE_ENV=development
    restart: on-failure
    image: rihbyne/whirlpool-fetch-dev:latest
    depends_on:
      - whirlpool-rmq
      - whirlpool-mongodb

  whirlpool-rmq:
    container_name: whirlpool-rmq
    hostname: whirlpool-rmq
    restart: on-failure
    image: rihbyne/whirlpool-rmq:latest
    ports:
      - "5672:5672"
      - "8080:15672"

  whirlpool-mongodb:
    container_name: whirlpool-mongodb
    image: rihbyne/whirlpool-mongodb:latest
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - /covered/whirlpool/mongodbdata/:/data/db

  whirlpool-postgres:
    container_name: whirlpool-postgres
    image: rihbyne/whirlpool-postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - /covered/whirlpool/postgresdata/:/var/lib/postgresql/data

  whirlpool-memcached:
    container_name: whirlpool-memcached
    image: memcached:1.5.16
    restart: on-failure
    ports:
      - "11211:11211"

 #  whirlpool-parse:
 #    container_name: whirlpool-parse
 #    image: rihbyne/whirlpool-parse-dev:latest
 #    restart: on-failure
 #    entrypoint: bash ./scripts/wait-for-it.sh
 #     environment:
 #       - NODE_ENV=development
 #       - CRAWL_ORDER_MAX_LIM=1
 #    depends_on:
 #      - whirlpool-rmq
 #      - whirlpool-mongodb
 #  
 #  whirlpool-contentseen:
 #    container_name: whirlpool-contentseen
 #    image: rihbyne/whirlpool-contentseen-dev:latest
 #    restart: on-failure
 #    entrypoint: bash ./scripts/wait-for-it.sh
 #    depends_on:
 #      - whirlpool-rmq
 #      - whirlpool-mongodb
 #      - whirlpool-postgres
 #  
 #  whirlpool-urlfilter:
 #    container_name: whirlpool-urlfilter
 #    image: rihbyne/whirlpool-urlfilter-dev:latest
 #    entrypoint: bash ./scripts/wait-for-it.sh
 #    environment:
 #      - PY_ENV=development
 #    restart: on-failure
 #    depends_on:
 #      - whirlpool-rmq
 #      - whirlpool-mongodb
 #      - whirlpool-postgres
 #  
 #  whirlpool-due:
 #    container_name: whirlpool-due
 #    image: rihbyne/whirlpool-due-dev:latest
 #    entrypoint: bash ./scripts/wait-for-it.sh
 #    environment:
 #      - PY_ENV=development
 #    restart: on-failure
 #    depends_on:
 #      - whirlpool-rmq
 #      - whirlpool-mongodb
 #      - whirlpool-postgres
 #  
 #  whirlpool-urlfrontier:
 #    container_name: whirlpool-urlfrontier
 #    image: rihbyne/whirlpool-urlfrontier-prod:latest
 #    entrypoint: "java -cp whirlpool-urlfrontier-1.0-SNAPSHOT-jar-with-dependencies.jar crawler.whirlpool.urlfrontier.Main"
 #    environment:
 #      - JAVA_ENV=development
 #    restart: on-failure
 #    depends_on:
 #      - whirlpool-rmq
