version: '3.7'

networks:
  default:
    external:
      name: whirlpool-net


services:

  whirlpool-fetch:
    container_name: whirlpool-fetch
    entrypoint: bash ./scripts/wait-for-it.sh
    build:
      context: ./
      dockerfile: Dockerfile
      target: whirlpool-fetch-dev
    restart: on-failure
    depends_on:
      - whirlpool-rmq
      - whirlpool-mongodb

  whirlpool-rmq:
    container_name: whirlpool-rmq
    hostname: whirlpool-rmq
    restart: on-failure
    image: rihbyne/whirlpool-rmq:latest
    ports:
      - "5672:5672"
      - "8080:15672"

  whirlpool-mongodb:
    container_name: whirlpool-mongodb
    image: rihbyne/whirlpool-mongodb:latest
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - /covered/whirlpool/mongodbdata/:/data/db

  whirlpool-postgres:
    container_name: whirlpool-postgres
    image: rihbyne/whirlpool-postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - /covered/whirlpool/postgresdata/:/var/lib/postgresql/data

  whirlpool-parse:
    container_name: whirlpool-parse
    image: rihbyne/whirlpool-parse-dev:latest
    restart: on-failure
    entrypoint: bash ./scripts/wait-for-it.sh
    depends_on:
      - whirlpool-rmq
      - whirlpool-mongodb

  whirlpool-contentseen:
    container_name: whirlpool-contentseen
    image: rihbyne/whirlpool-contentseen-dev:latest
    restart: on-failure
    entrypoint: bash ./scripts/wait-for-it.sh
    depends_on:
      - whirlpool-rmq
      - whirlpool-mongodb
      - whirlpool-postgres
